### ISSUE TITLE
Andrey Volosevich: Jefferies

### ISSUE THREAD

**Issue by aflies1** [promazo/ProMazo-Videos#12]
Video: (https://drive.google.com/open?id=1xFe1SxjGdX11fCNsPTqavotRv9B7frmp)

**Comment by vbongard** [comment]
Video pitch (this is on the shorter side, is that okay? Not sure how it should look now that we have the new spreadsheet/system): https://docs.google.com/document/d/1FWk3SkU22Wwdmr-54cMavRUS1R33WHx31TWMnJOGQwQ/edit?usp=sharing

**Comment by aflies1** [comment]
Pitch looks good. Go for editing @vbongard

**Comment by vbongard** [comment]
Short 2 cut 1: https://drive.google.com/file/d/1aIcEfU-wS1pJfU6baoWxaqIwpoNCji7u/view?usp=sharing

Sort 1 cut 1 pending

**Comment by vbongard** [comment]
Finally got the other cut exported and uploaded! https://drive.google.com/file/d/1nes_VDda6bwtolscL1nZqTpm3zlQE8ns/view?usp=sharing

**Comment by aflies1** [comment]
- I like the Jefferies logo, we should do that with more videos.

- Graphics are a good add.

- These seem really good, I'm going to send to Brett.

@vbongard

**Comment by aflies1** [comment]
@vbongard 

I love the idea of using the logo, but that we will need permission which may delay the approval significantly so I would take it out.
for the 3 min video, I would put me asking the question in there at 2:03. It seems like too big of a jump in the video.

-From Brett

**Comment by vbongard** [comment]
Short 1, cut 2: https://drive.google.com/file/d/1KblAl8fuK40WyJBaJLZlbVhJICi_7JCy/view?usp=sharing

Short 2, cut 2: https://drive.google.com/file/d/1bdhr3Xe1qXBFI5DlfTmWACJv5Nsn3A1F/view?usp=sharing

**Comment by jaahmuhl** [comment]
Hi Victoria,

I really like the video, the only issue is that I think it will take awhile
to get the Jefferies logo approved. Do you think you could remove those?

On another note with the Thuan video, they requested that you lower the
volume of the background music.

And I just talked with the head of the NBA Players Association and she said
she loved the video. So keep knocking it out of the park!

Best,

Brett

**Comment by vbongard** [comment]
Hi Brett, 

I'm not sure if you saw the updated cuts for the Jefferies videos, but I went ahead and took out the Jefferies logo on those. Will lower the background music on the Thuan video and re-upload. Glad to hear that it's going over well!

~Victoria

**Comment by jaahmuhl** [comment]
Oh ok. Sorry I don't get updates when that happens. No worries.

Also I did get a response from Giovanni. It looks like they will probably
go with someone who has experience in building finance videos, but not
finalized yet.

Have a great night.

Brett

**Comment by jaahmuhl** [comment]
Hi Victoria,

Would you mind sending me the link to the Andrey and Thuan videos when you
have a chance? I can't seem to locate where the final ones are.

Thanks.

Brett

**Comment by jaahmuhl** [comment]
Video: https://drive.google.com/file/d/1KblAl8fuK40WyJBaJLZlbVhJICi_7JCy/view?usp=sharing

Blurb:

"When you're going into an interview. Don't just be interviewed. Interview the company." (Andrey Volosevich)'s advice to all students to take control of the recruiting process and make sure the company is the right fit for them.

Interviewer: (Brett Hummel)

Editor: (Victoria Bongard)


#Jefferies, #interviews, #recruiting, #culture, #promazo, #promazoexecinterviews
