### ISSUE TITLE
100k Mentors App Demo

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/ProMazo-Videos#14]
https://drive.google.com/file/d/1RE4_F40OGDmuj61iTxo7OXQTF80fRR44/view?usp=sharing

@vbongard 
@aflies1

**Comment by vbongard** [comment]
Putting the link in ZenHub since it hasn't been updated here yet: https://drive.google.com/file/d/19Ht3P78LFG4hRgvsBvtzFxdGjPLg8TGX/view?usp=sharing
