### ISSUE TITLE
Rick McCathron (Hippo Insurance, Chief Insurance Officer)

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/ProMazo-Videos#15]
https://drive.google.com/drive/folders/1M5TVkeIiQdQW3dItaHdGWDdyXkRqVuy5?usp=sharing

@aflies1

**Comment by vbongard** [comment]
Hi Adam, here's the pitch! I think a lot of the stuff he says goes together well, so I'm pitching a slightly longer video (7-9 minutes). If you'd rather keep it shorter, I can cut it down :)

https://docs.google.com/document/d/1xOT1IoiJm78DBiOjifakzmt0djxt6yYR45lBsyTOuKU/edit?usp=sharing

**Comment by bryanace53** [comment]
The video is in the drive 

https://drive.google.com/drive/u/2/folders/1F9-yTtCbQ-T1v0vIPiEwLjKhLulaQEyq

**Comment by vbongard** [comment]
@aflies1 The Rick video is in ZenHub twice. Okay to delete this one so that we don't have duplicates?
