### ISSUE TITLE
Rick McCathron, Hippo

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/ProMazo-Videos#16]
https://drive.google.com/drive/folders/1bj7_4tz32KVAIQuzKsm_DX8G-aLUbJUs?usp=sharing

@aflies1

**Comment by bryanace53** [comment]
The Video is in the drive

https://drive.google.com/drive/u/2/folders/1F9-yTtCbQ-T1v0vIPiEwLjKhLulaQEyq

**Comment by jaahmuhl** [comment]
@bryanace53 I don't see this video in there

**Comment by vbongard** [comment]
Hi Adam, did we ever get the video of the other interviewer? I don't see it in the folder so I still just have the placeholder. Here are the videos with placeholders:

Video about culture and opportunities at Hippo: https://drive.google.com/file/d/10txz9Mypo40mNPOP13BzK5mF5w3omTeo/view?usp=sharing
Video about the workforce and luck: https://drive.google.com/file/d/1TlG-JYCrgvPVm9VuocAcbvOWzI8Lduh9/view?usp=sharing

I can add more fun graphics to the multi-screen bits and make it more exciting, but I didn't want to do that before I know that we'll have the missing angle.

**Comment by vbongard** [comment]
I spoke with Brett and it turns out we don't have the other angle. So, I'm reverting back to the style that I've used previously:

 Video 1: https://drive.google.com/file/d/1WbzPpmT0CLTtnQ9bnGflQppJKuKbGNVn/view?usp=sharing
Video 2: https://drive.google.com/file/d/1xM-yBY5sXeazmWUCHvnhtSQpHLFk5Y1-/view?usp=sharing

**Comment by vbongard** [comment]
Here are the videos revised with Brett's comments:

Career: https://drive.google.com/file/d/1LTBRw0zNTrkIaWb2I3eh-0dhKr0_y7_8/view?usp=sharing

Hiring: https://drive.google.com/file/d/1LnhanHnOggXDg79veHQUxZxZXBunz-oW/view?usp=sharing

Leadership: https://drive.google.com/file/d/1AyLNOHbLKq5T6ZhCM0Rvk4oLjK4yS8N8/view?usp=sharing

**Comment by vbongard** [comment]
Here's the edited career video per Brett's edits: https://drive.google.com/file/d/1QizRVFUl88ObrhKXm2G-uUnT2-8mdyWg/view?usp=sharing

**Comment by jaahmuhl** [comment]
For This Video: https://drive.google.com/file/d/1lrvxKfMKVm7qrB7DUwrySxQEmWNyQBGo/view

Blurb:

What’s the secret sauce to becoming a successful leader? 

1. Intellectual curiosity
2. A sense of urgency in everything you do
3. Being in the right place at the right time 

Hear (Rick McCathron), the President of Hippo, the company transforming home insurance from the lens of the customer, share his quick tips on how to succeed in business.


Interviewer: (Brett Hummel) & (Baptiste Bouvier)

Editor: (Victoria Bongard)

#secrettosuccess, #leadership, #hippo, #promazoexecinterviews, #promazo

**Comment by vbongard** [comment]
Updated leadership video with edits from Hippo: https://drive.google.com/file/d/1l5BXE0auAoq_idZtHVbITHCSQFIkRJVN/view?usp=sharing
