### ISSUE TITLE
Bruce Starnes-Target

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/ProMazo-Videos#23]
https://drive.google.com/drive/folders/15a90IgdVYIPsKsEZ-GNR4Lw6AV0Yx-PN?usp=sharing

@aflies1

**Comment by jaahmuhl** [comment]
@bryanace53 I didn't see a video link here. Could you post it when you have a chance?

**Comment by bryanace53** [comment]
My bad here is the video, I also fixed the background. 

https://drive.google.com/drive/u/1/folders/1RsAHySSv22TXUQx2Y2IEQWi4ca2lrMBN

**Comment by jaahmuhl** [comment]
:10-Change question to: How did you understand what an employer is looking for?

All of my questions you don't see me and it breaks the third wall for the audience. I have to be seen in the video if we are going to have me ask questions.

**Comment by bryanace53** [comment]
Hey Brett,

I fixed the video let me know what you think !

https://drive.google.com/drive/u/1/folders/1NyWDJhv04giGlEtrRvEZVnPOcoJLDrs1

**Comment by jaahmuhl** [comment]
@bryanace53 at min 1:13 the video still has me speaking without showing me.

I also dont get why it shows the questions and then shows me. Can we just do a cut to me with a transition?

**Comment by jaahmuhl** [comment]
[https://drive.google.com/drive/u/1/folders/1NyWDJhv04giGlEtrRvEZVnPOcoJLDrs1]
Blurb:

One theme in the career for Bruce the VP of Partnerships and New Business Development at Target, is always trying to gain a breadth of experiences. He thinks it is critical to gain these experiences if you aim to become a leader of large teams. Learn how he did it and his other advice on starting your career.

Interviewer: (Brett Hummel)

Videographer: (Bryan Acevedo)

#target, #promazoexecinterviews, #promazo, #jobexperience, #breadthvsdepth
