### ISSUE TITLE
Ed Roussel-Wall Street Journal

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/ProMazo-Videos#27]
https://drive.google.com/drive/folders/1U6lEYBrASvgKgPIS8gK_XuJJcN5ClEcD?usp=sharing

@aflies1

**Comment by bryanace53** [comment]
Here is the video 

https://drive.google.com/drive/u/1/folders/1vHuOsxeRdhBBapGjnFDAvN5Q9PwNfVFA

**Comment by jaahmuhl** [comment]
@bryanace53 at 6 seconds in, it does not show me but I am speaking. We should either do it so that it never shows me speaking or hearing my voice and just the text questions or it has me in the videos without the text questions.

This also happens at 2:55.

**Comment by jaahmuhl** [comment]
Blurb
@mikepromazo 

As a young professional, it can be difficult to know when to present an idea to your boss. Turns out you can increase the chances of getting your ideas pushed through based on the part of the innovation cycle your company is currently in...

"One thing I've observed is the willingness to experiment and to innovate ebbs and flows in an organization. You have to be sensitive to that ebb and flow, which doesn't mean that you go with the ebb and flow, but you have to know when [to push the envelope]."

(Ed Roussell)
Chief Innovation Officer for the Wall Street Journal

Interviewer: (Baptiste Bouvier) & (Brett Hummel)

Videographer: (Bryan Acevedo)

#careermanagement, #innovation, #promazo, #promazoexecinterviews,

**Comment by bryanace53** [comment]
Ok I will fix this

**Comment by bryanace53** [comment]
Hey Brett,

Here is the fixed video.

https://drive.google.com/drive/u/1/folders/1U6lEYBrASvgKgPIS8gK_XuJJcN5ClEcD
