### ISSUE TITLE
Troy Fenner, SVP of Human Resources at Roku

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/ProMazo-Videos#33]
@mikepromazo 

Blurb: https://www.youtube.com/watch?v=GKT1RIdAJAQ

Roku has exploded as more and more content is consumed online. Ever wondered what a company like that looks for in their potential hires? Troy Fenner, the SVP of Human Resources, gives students insight into what they look in candidates.

Interviewer: (Brett Hummel)

#gethiredinsiliconvalley, #firstjob, #interview, #promazoexecinterviews, #promazo, #roku

**Comment by mikepromazo** [comment]
https://drive.google.com/drive/u/4/folders/1OURxDLIhxTQGM5548FcdW9uNHhjUF-X5

 "Roku (short-company) 1" - post first
