### ISSUE TITLE
Scott Price - Chief Strategy & Transformation Officer UPS

### ISSUE THREAD

**Issue by aflies1** [promazo/ProMazo-Videos#7]
Video - https://drive.google.com/file/d/17p_9wf-D6v2JYxGRWDgRgUD0Cd_fwprA/view?usp=sharing

Research - https://docs.google.com/document/d/16URH60FYsEIMWHophIhjywDc7q5eaDx5Z48M2c9COk4/edit

**Comment by aflies1** [comment]
- [ ] Research

 

- [ ] Notes on Video

 

- [ ] Video Pitch / Storyboard

 

- [ ] First Draft

 

- [ ] Edits

 

- [ ] Final Draft

**Comment by bryanace53** [comment]
Video is in the drive 


https://drive.google.com/drive/u/2/folders/1WffiFn0C_iaQRzc732clRBUtQz2yKfij

**Comment by jaahmuhl** [comment]
@bryanace53 @aflies1 

I think this is a very good video. I think we need to do a discussion on him though because he has some absolutely amazing nuggets (I'm thinking multiple videos)

For the video you created:
the first title text: Change to 'Tell Us a Little About Yourself'. I am also questioning if we want this in the video because the back half is spectacular. Or should it be its own video. Let's discuss.

2:27-the video cuts the volume of the speaker too quickly

6:00-Change text to: What advise do you have for young people entering the professional world?

**Comment by bryanace53** [comment]
https://drive.google.com/drive/u/1/folders/1WffiFn0C_iaQRzc732clRBUtQz2yKfij


New video uploaded

**Comment by jaahmuhl** [comment]
@bryanace53 
Scott Price Fin: The title should be:
Scott Price,
President UPS International.

Q1: There is a space between the ? and the last word (it seems to be in each question).
I have a laugh in there in the middle and wanted to see if we could cut that out.

I would cut out the first question and make it its own video (tell us about your early career)

Q2: How do you have a successful career?

Q3: How do you become a leader in a company?

SOCIAL MEDIA 
the spaces between the questions are still there.

**Comment by bryanace53** [comment]
I fixed the videos let me know if its good. 


https://drive.google.com/drive/u/1/folders/1Uk3hteSF0OrPf4Fh2Z_Fml1GYslZR97l

**Comment by jaahmuhl** [comment]
@bryanace53 
@mikepromazo 

SOCIAL MEDIA VIDEO:
The question at the end of the question still has a space at the end of the question between the last word and the question mark. 

FIN:
I like how you cut out the first part of the career track, but I thought you were going to port that first question from the original video (tell us about yourself) and make it its own standalone video.

**Comment by bryanace53** [comment]
Hey Brett,

I fixed the social media video and uploaded the standalone video which was the (tell us about yourself).

https://drive.google.com/drive/u/1/folders/1_0PsVQK0eiXoJ-mFQgS7Yd2PbCqBWjAK

**Comment by jaahmuhl** [comment]
@bryanace53  

https://drive.google.com/drive/u/1/folders/1_0PsVQK0eiXoJ-mFQgS7Yd2PbCqBWjAK

at min 2:05 I laugh and I was wondering if you can take this out of the audio.

For: https://drive.google.com/drive/u/1/folders/1_0PsVQK0eiXoJ-mFQgS7Yd2PbCqBWjAK
Can you change the first question to: How do you know if the job is the right fit?

Everything else looks great.

**Comment by jaahmuhl** [comment]
Blurb for https://drive.google.com/file/d/151vlHSDFOlOOU4XHrvcgMUrAs6dDOCN1/view?usp=sharing
How do you become successful at any company around the world? Follow (Scott Price)'s model to joining a new company. Learn the tips and tricks a global leader used to rise to the top and become the Chief Strategy Officer of (UPS).

Interviewer: (Brett Hummel)
Editor: (Bryan Acevedo)

#careeradvice, #howtobesuccessful, #promazoexecinterview, #youngprofessional, #ups
